### ISSUE TITLE
audience

### ISSUE THREAD

**Issue by dadahl** [w3c/voiceinteraction#2]
from Jim Larson's email: 
Who is the audience of this document?

resolution: add a sentence in the introduction about the audience.
(see minutes March 10) [https://lists.w3.org/Archives/Public/public-voiceinteraction/2021Mar/0003.html](url)

**Comment by jcstine** [comment]
My apologies: I am unsure as to which file I should submit a pull request.  The desire of this issue is to suggest that the proposed architecture has multiple prospective audiences -- not only developers, but enterprises seeking guidance as to architectures of interoperability and optimum flexibility, consultancies wishing to offer clients a "best-practices" checklist of capabilities, and entrepreneurs seeking an "open" architecture upon which a capabilities-services practice could be built.  This paper will also serve as a reference point for analysts and commentators who will be seeking to referee the looming tug of war as to the definition of voice assistant/conversational agent interoperability.

**Comment by dadahl** [comment]
Hi Jon,

Good question – the right file is our main Architecture 1.1 document at https://github.com/w3c/voiceinteraction/blob/master/voice%20interaction%20drafts/paArchitecture-1-1.htm. 

Your insights look like great additions to the document.

Best regards,

Debbie

**Comment by dadahl** [comment]
Completed with Jon's update to the audience section.
