### ISSUE TITLE
Does payment information have to go through personal assistants?

### ISSUE THREAD

**Issue by dadahl** [w3c/voiceinteraction#59]
There are a few scenarios, we need to discuss

**Comment by GerardChollet2** [comment]
Not sure how to handle that, sorry ! This should be a collective effort,... 

Best, Gérard 
​​_____________________________________________________________________ 
Gérard ***@***.*** 
Institut Polytechnique de Paris, IMT-TSP, 9 rue Charles Fourier, 91011 Evry 
Tel: +33 1 75319628 , http://perso.telecom-paristech.fr/~chollet/ 
_____________________________________________________________________ 



De: "Deborah Dahl" ***@***.***> 
À: "w3c/voiceinteraction" ***@***.***> 
Cc: "Gerard CHOLLET" ***@***.***>, "Assign" ***@***.***> 
Envoyé: Mercredi 14 Août 2024 17:05:53 
Objet: Re: [w3c/voiceinteraction] Does payment information have to go through personal assistants? (Issue #59) 





Assigned [ https://github.com/w3c/voiceinteraction/issues/59 | #59 ] to [ https://github.com/GerardChollet2 | @GerardChollet2 ] .

**Comment by GerardChollet2** [comment]
Yes, we should discuss as a group. This is really a placeholder to make sure that we don’t lose track of it.

**Comment by nwhysel** [comment]
It is possible for assistants to connect to wallets. I don’t know what the tech looks like exactly, but I know people at Kantara Initiative who would. It’s likely it would delegate to a selected wallet through some transaction id, rather than actually passing transaction data.NoreenOn Aug 14, 2024, at 1:11 PM, GerardChollet2 ***@***.***> wrote:﻿
Yes, we should discuss as a group. This is really a placeholder to make sure that we don’t lose track of it.



 



From: Gerard CHOLLET ***@***.***> 

Sent: Wednesday, August 14, 2024 11:43

To: w3c/voiceinteraction ***@***.***>; Deborah Dahl ***@***.***>

Cc: w3c/voiceinteraction ***@***.***>; Assign ***@***.***>; Gerard CHOLLET ***@***.***>; hugues ***@***.***>

Subject: Re: [w3c/voiceinteraction] Does payment information have to go through personal assistants? (Issue #59)



 



Not sure how to handle that, sorry ! This should be a collective effort,...



 



Best,                Gérard



​​_____________________________________________________________________

Gérard ***@***.***

       Institut Polytechnique de Paris, IMT-TSP, 9 rue Charles Fourier, 91011 Evry

                Tel: +33 1 75319628 , http://perso.telecom-paristech.fr/~chollet/

_____________________________________________________________________



 



  _____  



De: "Deborah Dahl" ***@***.*** ***@***.***> >

À: "w3c/voiceinteraction" ***@***.*** ***@***.***> >

Cc: "Gerard CHOLLET" ***@***.*** ***@***.***> >, "Assign" ***@***.*** ***@***.***> >

Envoyé: Mercredi 14 Août 2024 17:05:53

Objet: Re: [w3c/voiceinteraction] Does payment information have to go through personal assistants? (Issue #59)



 



Assigned #59 <https://github.com/w3c/voiceinteraction/issues/59>  to @GerardChollet2 <https://github.com/GerardChollet2> .

**Comment by GerardChollet2** [comment]
I see [ https://www.myvirtualwallet.co.uk/virtual-wallet-for-personal-assistants/ | https://www.myvirtualwallet.co.uk/virtual-wallet-for-personal-assistants/ ] and [ https://kantarainitiative.org/ | https://kantarainitiative.org/ ] , thanks for the links ! 
See also [ https://peppervirtualassistant.com/blog/secure-and-efficient-digital-money-transfers-a-virtual-assistants-guide/ | https://peppervirtualassistant.com/blog/secure-and-efficient-digital-money-transfers-a-virtual-assistants-guide/ ] 
[ https://www.linkedin.com/pulse/virtual-assistants-12-tips-go-from-valet-wallet-subramaniam-egain/ | https://www.linkedin.com/pulse/virtual-assistants-12-tips-go-from-valet-wallet-subramaniam-egain/ ] 
[ https://www.financemagnates.com/institutional-forex/technology/the-use-of-chatbots-and-virtual-assistants-in-financial-services/ | https://www.financemagnates.com/institutional-forex/technology/the-use-of-chatbots-and-virtual-assistants-in-financial-services/ ] 

Best, Gérard 
​​_____________________________________________________________________ 
Gérard ***@***.*** 
Institut Polytechnique de Paris, IMT-TSP, 9 rue Charles Fourier, 91011 Evry 
Tel: +33 1 75319628 , http://perso.telecom-paristech.fr/~chollet/ 
_____________________________________________________________________ 



De: "nwhysel" ***@***.***> 
À: "w3c" ***@***.***> 
Cc: "Gerard CHOLLET" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Jeudi 15 Août 2024 02:13:59 
Objet: Re: [w3c/voiceinteraction] Does payment information have to go through personal assistants? (Issue #59) 



It is possible for assistants to connect to wallets. I don’t know what the tech looks like exactly, but I know people at Kantara Initiative who would. 
It’s likely it would delegate to a selected wallet through some transaction id, rather than actually passing transaction data.Noreen 
On Aug 14, 2024, at 1:11 PM, GerardChollet2 ***@***.***> wrote: 
Yes, we should discuss as a group. This is really a placeholder to make sure that we don’t lose track of it. 







From: Gerard CHOLLET ***@***.***> 

Sent: Wednesday, August 14, 2024 11:43 

To: w3c/voiceinteraction ***@***.***>; Deborah Dahl ***@***.***> 

Cc: w3c/voiceinteraction ***@***.***>; Assign ***@***.***>; Gerard CHOLLET ***@***.***>; hugues ***@***.***> 

Subject: Re: [w3c/voiceinteraction] Does payment information have to go through personal assistants? (Issue #59) 







Not sure how to handle that, sorry ! This should be a collective effort,... 







Best, Gérard 



​​_____________________________________________________________________ 

Gérard ***@***.*** 

Institut Polytechnique de Paris, IMT-TSP, 9 rue Charles Fourier, 91011 Evry 

Tel: +33 1 75319628 , http://perso.telecom-paristech.fr/~chollet/ 

_____________________________________________________________________ 







_____ 



De: "Deborah Dahl" ***@***.*** ***@***.***> > 

À: "w3c/voiceinteraction" ***@***.*** ***@***.***> > 

Cc: "Gerard CHOLLET" ***@***.*** ***@***.***> >, "Assign" ***@***.*** ***@***.***> > 

Envoyé: Mercredi 14 Août 2024 17:05:53 

Objet: Re: [w3c/voiceinteraction] Does payment information have to go through personal assistants? (Issue #59) 







Assigned #59 <https://github.com/w3c/voiceinteraction/issues/59> to @GerardChollet2 <https://github.com/GerardChollet2> .

**Comment by schnelle** [comment]
Privacy will be handled in #60 . This use case is intersting but maybe too specific to be explored in detail in the architecture document.
